# general settings
name: MCGAN_OldPhtots_400k
model_type: MCModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0
# dataset and data loader settings
datasets:
  train:
    name: OldPhotos
    type: PairedImageDataset
    dataroot_gt: datasets/FusionOldPhotos-x2/GT
    dataroot_lq: datasets/FusionOldPhotos-x2/Old
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 64
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: OldPhotos-test
    type: PairedImageDataset
    dataroot_gt: datasets/ValOldPhotos/GT
    dataroot_lq: datasets/ValOldPhotos/Old
    io_backend:
      type: disk

# network structures
network_g:
  type: MCGAN
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 32

network_d:
  type: StyleNLayerDiscriminator
  input_nc: 3
  ndf: 64
  n_layers: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  pretrain_network_d: ~
  strict_load_d: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: !!float 1
    style_weight: 0.5
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3
  KLdiv_opt:
    type: KLLoss
    loss_weight: !!float 0

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  overlap: 10
  val_scale: 1
  valid_patch: 64
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
